{
 "title": "PStore",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (client, code)(rate(pstore_rcount[$__rate_interval]))",
     "legendFormat": "{{client}} - {{code}}"
    }
   ]
  },
  {
   "title": "Read Diffs",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pstore_rcount_diffs)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(pstore_rcount_latency_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(pstore_rcount_latency_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}