apiVersion: v1
kind: Service
metadata:
  name: pstore
  namespace: pstore
  labels:
    app: pstore
spec:
  type: NodePort
  metadata:
    labels:
      app: pstore
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8081
      targetPort: 8081
  selector:
    app: pstore
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pstore
  namespace: pstore
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - pstore
  selector:
    matchLabels:
      app: pstore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pstore
  namespace: pstore
spec:
  selector:
    matchLabels:
      app: pstore
  replicas: 3
  template:
    metadata:
      labels:
        app: pstore
    spec:
      containers:
        - name: pstore
          image: registry.brotherlogic-backend.com/brotherlogic/pstore:0.24.0 # {"$imagepolicy": "flux-system:pstore"}
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
